import { useState } from 'react';
import { Bike, CheckCircle2, Database, Download, RotateCcw, Upload, WalletCards } from 'lucide-react';
import { formatCurrency } from '../lib/formatters.js';

export default function SettingsPage({ bikeTypes, bikes, transactions, getRate, onRateChange, onExport, onImport, onReset }) {
  const [activeView, setActiveView] = useState('pricing');
  const [confirmReset, setConfirmReset] = useState(false);

  return (
    <div className="space-y-5">
      <div className="flex gap-1 overflow-x-auto border-b border-slate-200" role="tablist" aria-label="Kategori pengaturan">
        <button type="button" role="tab" aria-selected={activeView === 'pricing'} onClick={() => setActiveView('pricing')} className={`inline-flex shrink-0 items-center gap-2 border-b-2 px-4 py-3 text-xs font-black ${activeView === 'pricing' ? 'border-cyan-600 text-cyan-700' : 'border-transparent text-slate-700'}`}><WalletCards size={16} /> Harga & Modal</button>
        <button type="button" role="tab" aria-selected={activeView === 'data'} onClick={() => setActiveView('data')} className={`inline-flex shrink-0 items-center gap-2 border-b-2 px-4 py-3 text-xs font-black ${activeView === 'data' ? 'border-cyan-600 text-cyan-700' : 'border-transparent text-slate-700'}`}><Database size={16} /> Data & Backup</button>
      </div>

      {activeView === 'pricing' ? (
        <section className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
          <div className="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-base font-black text-slate-950">Harga Dinamis per Tipe</h2><p className="mt-1 text-xs font-semibold text-slate-500">Modal bengkel dan harga jual ke tamu</p></div><span className="inline-flex items-center gap-1.5 rounded-md bg-emerald-50 px-3 py-1.5 text-[10px] font-black uppercase tracking-wide text-emerald-700"><CheckCircle2 size={14} /> Tersimpan Otomatis</span></div>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[760px] border-collapse text-left"><thead><tr className="border-b border-slate-200 bg-slate-50"><th className="px-5 py-3 text-[10px] font-black uppercase tracking-wide text-slate-500">Tipe Sepeda</th><th className="px-5 py-3 text-[10px] font-black uppercase tracking-wide text-slate-500">Unit</th><th className="px-5 py-3 text-[10px] font-black uppercase tracking-wide text-slate-500">Modal</th><th className="px-5 py-3 text-[10px] font-black uppercase tracking-wide text-slate-500">Harga Tamu</th><th className="px-5 py-3 text-[10px] font-black uppercase tracking-wide text-slate-500">Laba</th></tr></thead><tbody className="divide-y divide-slate-100">{bikeTypes.map((type) => { const rate = getRate(type); const count = bikes.filter((bike) => bike.type === type).length; const profit = rate.price - rate.cost; return <tr key={type} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="text-sm font-black text-slate-900">{type}</p></td><td className="px-5 py-4"><span className="inline-flex items-center gap-1.5 text-xs font-black text-slate-600"><Bike size={14} /> {count}</span></td><td className="px-5 py-4"><input type="number" min="0" step="1000" value={rate.cost} onChange={(event) => onRateChange(type, 'cost', event.target.value)} aria-label={`Modal ${type}`} className="w-full rounded-md border border-slate-200 px-3 py-2.5 text-sm font-black text-rose-700 outline-none focus:border-cyan-400 focus:ring-4 focus:ring-cyan-100" /></td><td className="px-5 py-4"><input type="number" min="0" step="1000" value={rate.price} onChange={(event) => onRateChange(type, 'price', event.target.value)} aria-label={`Harga tamu ${type}`} className="w-full rounded-md border border-slate-200 px-3 py-2.5 text-sm font-black text-emerald-700 outline-none focus:border-cyan-400 focus:ring-4 focus:ring-cyan-100" /></td><td className="px-5 py-4"><p className={`text-sm font-black ${profit >= 0 ? 'text-cyan-700' : 'text-rose-700'}`}>{formatCurrency(profit)}</p></td></tr>; })}</tbody></table>
          </div>
        </section>
      ) : (
        <div className="grid gap-5 lg:grid-cols-2">
          <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-md bg-cyan-50 text-cyan-700"><Database size={21} /></div><h2 className="mt-4 text-base font-black text-slate-950">Backup Operasional</h2><div className="mt-4 grid grid-cols-2 border-y border-slate-100 py-4"><div><p className="text-2xl font-black text-slate-950">{bikes.length}</p><p className="mt-1 text-xs font-semibold text-slate-500">unit armada</p></div><div><p className="text-2xl font-black text-slate-950">{transactions.length}</p><p className="mt-1 text-xs font-semibold text-slate-500">transaksi</p></div></div><div className="mt-5 flex flex-col gap-2 sm:flex-row"><button type="button" onClick={onExport} className="inline-flex flex-1 items-center justify-center gap-2 rounded-md bg-slate-950 px-4 py-3 text-xs font-black text-white"><Download size={16} /> Unduh Backup</button><label className="inline-flex flex-1 cursor-pointer items-center justify-center gap-2 rounded-md bg-cyan-50 px-4 py-3 text-xs font-black text-cyan-700 ring-1 ring-cyan-200"><Upload size={16} /> Impor Backup<input type="file" accept="application/json,.json" onChange={onImport} className="sr-only" /></label></div></section>
          <section className="rounded-lg border border-rose-200 bg-white p-5 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-md bg-rose-50 text-rose-700"><RotateCcw size={21} /></div><h2 className="mt-4 text-base font-black text-slate-950">Pulihkan Data Demo</h2><p className="mt-2 text-sm font-semibold leading-6 text-slate-500">Mengganti armada, transaksi, dan harga saat ini dengan data awal aplikasi.</p>{confirmReset ? <div className="mt-5 flex gap-2"><button type="button" onClick={() => { onReset(); setConfirmReset(false); }} className="rounded-md bg-rose-600 px-4 py-3 text-xs font-black text-white">Ya, Pulihkan</button><button type="button" onClick={() => setConfirmReset(false)} className="rounded-md bg-slate-100 px-4 py-3 text-xs font-black text-slate-700">Batal</button></div> : <button type="button" onClick={() => setConfirmReset(true)} className="mt-5 inline-flex items-center gap-2 rounded-md bg-rose-50 px-4 py-3 text-xs font-black text-rose-700 ring-1 ring-rose-200"><RotateCcw size={16} /> Reset Data</button>}</section>
        </div>
      )}
    </div>
  );
}
